// <auto-generated />
using System;
using System.Collections.Generic;
using JetFlight.ApplicationDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JetFlight.ApplicationDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20260627122640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsSuperadmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AdminRole");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminToRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<byte?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolveMessage")
                        .HasColumnType("text");

                    b.Property<string>("ResolveSignature")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUsAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactUsId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactUsId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ContactUsAttachments");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<byte>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<int>>("CustomerCouponIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("ResolveMessage")
                        .HasColumnType("text");

                    b.Property<string>("ResolveSignature")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.FeedbackAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FeedbacksAttachments");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.LogHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedFrom")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedTo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("LogsHistory");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.MediaFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RootPage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledPublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OriginId");

                    b.HasIndex("ParentId");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("text");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("ImageSize")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OriginId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReadDurationMin")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OriginId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PostsTags");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.PostToTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.RFM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmountId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int?>("CountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AmountId");

                    b.HasIndex("CountId");

                    b.HasIndex("PeriodId");

                    b.ToTable("RFMs");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Range<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("From")
                        .HasColumnType("integer");

                    b.Property<int>("To")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Range<int>");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ResetPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("AuthCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ResetPassword");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.RoleToPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PermissionsId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.RolesPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("Crud")
                        .HasColumnType("smallint");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("RolesPermissions");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OriginId")
                        .HasColumnType("integer");

                    b.Property<int?>("PageId")
                        .HasColumnType("integer");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OriginId");

                    b.HasIndex("PageId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.SectionField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<bool?>("Extendable")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int?>("MediaFilesId")
                        .HasColumnType("integer");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedTitle")
                        .HasColumnType("text");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("SubSectionTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MediaFilesId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionField");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.SeoMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SeoMeta");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<byte?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<string>("MapLink")
                        .HasColumnType("text");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MediaFileId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Target", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("AgeTo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageCheckAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageCheckAmountTo")
                        .HasColumnType("numeric");

                    b.Property<int?>("AverageCheckPositionsFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageCheckPositionsTo")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageFrequencyTimes")
                        .HasColumnType("integer");

                    b.Property<byte?>("BranchId")
                        .HasColumnType("smallint");

                    b.Property<List<string>>("CategoryCodes")
                        .HasColumnType("text[]");

                    b.Property<int?>("CheckCountFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("CheckCountTo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfBirthFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("DayOfBirthTo")
                        .HasColumnType("integer");

                    b.Property<int?>("FrequencyType")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeOnBirthdayOnly")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("ManufacturerCodes")
                        .HasColumnType("text[]");

                    b.Property<int?>("MonthOfBirthFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("MonthOfBirthTo")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Period")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ProductAmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProductAmountTo")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RegisteredDateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RegisteredDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegisteredDaysFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("RegisteredDaysTo")
                        .HasColumnType("integer");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingPeriodFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingPeriodTo")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("ShoppingTimeFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ShoppingTimeTo")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearOfBirthFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("YearOfBirthTo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.TargetToCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TargetId");

                    b.ToTable("TargetToCity");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.TargetToRFM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RFMId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RFMId");

                    b.HasIndex("TargetId");

                    b.ToTable("TargetToRFM");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.WorkingHours", b =>
                {
                    b.Property<int>("WorkingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkingHoursId"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("interval");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("WorkingHoursId");

                    b.HasIndex("StoreId");

                    b.HasIndex("WorkingHoursId")
                        .IsUnique();

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminToRole", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUs", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUsAttachment", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUs", "ContactUs")
                        .WithMany("Attachments")
                        .HasForeignKey("ContactUsId");

                    b.Navigation("ContactUs");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Feedback", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.Navigation("Assignee");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.FeedbackAttachment", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Feedback", "Feedback")
                        .WithMany("Attachments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.LogHistory", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", "Origin")
                        .WithMany("Versions")
                        .HasForeignKey("OriginId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Origin");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Post", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Post", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.PostToTag", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.PostTag", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.RFM", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Range<int>", "Amount")
                        .WithMany()
                        .HasForeignKey("AmountId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Range<int>", "Count")
                        .WithMany()
                        .HasForeignKey("CountId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Range<int>", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");

                    b.Navigation("Amount");

                    b.Navigation("Count");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ResetPassword", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.RoleToPermission", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.RolesPermission", "Permissions")
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminRole", "Role")
                        .WithMany("RoleToPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Section", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Section", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Origin");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.SectionField", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.MediaFiles", "MediaFiles")
                        .WithMany()
                        .HasForeignKey("MediaFilesId");

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Section", "Section")
                        .WithMany("SectionFields")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MediaFiles");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Store", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.City", "City")
                        .WithMany("Stores")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.MediaFiles", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId");

                    b.Navigation("City");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.TargetToCity", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Target", "Target")
                        .WithMany("Cities")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.TargetToRFM", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.RFM", "RFM")
                        .WithMany()
                        .HasForeignKey("RFMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Target", "Target")
                        .WithMany("RFMs")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RFM");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.WorkingHours", b =>
                {
                    b.HasOne("JetFlight.ApplicationDataAccess.Entities.DataContext.Store", "Store")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.AdminRole", b =>
                {
                    b.Navigation("RoleToPermissions");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.City", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.ContactUs", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Feedback", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Page", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sections");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Section", b =>
                {
                    b.Navigation("SectionFields");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Store", b =>
                {
                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("JetFlight.ApplicationDataAccess.Entities.DataContext.Target", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("RFMs");
                });
#pragma warning restore 612, 618
        }
    }
}
